### PR TITLE
Fix ios_x64 platform libs cache for iOS 11 and 12

### PR DESCRIPTION
**Pull request by SvyatoslavScherbina**
Fixes https://youtrack.jetbrains.com/issue/KT-38045

### CODE REVIEW

**Comment by benasher44** [comment]
Is there a workaround that can be applied locally for this one? We've upgraded locally, and now we find we can't test on iOS 12. Thanks!

**Comment by SvyatoslavScherbina** [comment]
> Is there a workaround that can be applied locally for this one? We've upgraded locally, and now we find we can't test on iOS 12. Thanks!

Sure! Please disable compiler caches using Gradle project property `kotlin.native.cacheKind=none`.
Should be fixed in 1.4.

**Comment by benasher44** [comment]
Thanks!

**Comment by SvyatoslavScherbina** [comment]
Fixes https://youtrack.jetbrains.com/issue/KT-38045

**Comment by SvyatoslavScherbina** [comment]
The fix is also backported to 1.3.7x branch: https://github.com/JetBrains/kotlin-native/pull/4071

**Pull request merged**
