### PR TITLE
Support Linux x64 and RaspberryPi cross-compilation on Windows and macOS hosts.

### PR DESCRIPTION
**Pull request by olonho**

### CODE REVIEW

**Comment by msink** [comment]
Maybe first cleanup Linux target a little?
At least split toolchain and sysroot to separate artifacts.

**Comment by msink** [comment]
Also - can be `llvm-ar` used instead of plain `ar` from platform binutils?

**Comment by msink** [comment]
BTW, I have canadian-cross-compiled `target-gcc-toolchain-3-linux-x86-64` for mingw host, but not sure it is needed.

**Comment by olonho** [comment]
Nope, cross-compiler in that direction (mingw->Linux) not needed so far, but maybe mingw compiler hosted on Linux would make sense eventually.

**Pull request merged**
