### PR TITLE
Replace iPhone by iOS in doc

### PR DESCRIPTION
**Pull request by LouisCAD**

### CODE REVIEW

**Comment by SvyatoslavScherbina** [comment]
The same is applicable to Kotlin/Native: https://github.com/JetBrains/kotlin/pull/2505#issuecomment-518123712

**Comment by LouisCAD** [comment]
@SvyatoslavScherbina Regarding this issue, this branch (`v1.3.0-fixes`) is the one the edit on GitHub button was pointing to. Maybe the website needs to be updated to point to the `master` branch instead?

**Comment by SvyatoslavScherbina** [comment]
Not sure if this is relevant to the PR being discussed.
Feel free to share your concerns e.g. with https://github.com/JetBrains/kotlin-web-site

**Comment by LouisCAD** [comment]
I clicked "Edit on GitHub", and submitted this. If you're not accepting
edits, then the button on the website should be removed, or updated to
target the appropriate branch.

**Comment by SvyatoslavScherbina** [comment]
Please rebase this PR to master.

**Comment by LouisCAD** [comment]
This PR was previously merged in this branch: https://github.com/JetBrains/kotlin-native/pull/3195

You are contradicting the Kotlin website and your coworker @olonho.
I let you pick up the fix yourself and find an agreement on which branch is used for fixes coming from the website.

Note that rebasing isn't possible from GitHub interface, and cloning the whole repository for just a simple typo fix is a no go for me. The harder you make it to fix typos, the more you'll leave on the website. That's why I expect the "Edit on GitHub" button from the website to target the appropriate branch that is deployed after merging.

**Comment by SvyatoslavScherbina** [comment]
> This PR was previously merged in this branch: #3195
> You are contradicting the Kotlin website and your coworker @olonho.

And that merge seems wrong to me: as I can clearly see, that patch didn't get into master. Most likely wrong branch wasn't noticed.

**Pull request closed without merging**
