### PR TITLE
Update PLATFORM_LIBS.md

### PR DESCRIPTION
**Pull request by LouisCAD**

### CODE REVIEW

**Comment by SvyatoslavScherbina** [comment]
Thanks for noticing.
Wrong branch, see your report here: https://youtrack.jetbrains.com/issue/KT-33165
Opened new PR for master: https://github.com/JetBrains/kotlin-native/pull/4358

**Comment by LouisCAD** [comment]
@SvyatoslavScherbina This branch is where the "Edit on GitHub" button points to on the website. Should I open an issue for that?

**Comment by SvyatoslavScherbina** [comment]
@LouisCAD Please refer to my comment above.
You have already opened the issue for that: https://youtrack.jetbrains.com/issue/KT-33165

**Comment by LouisCAD** [comment]
Ah yes, it's already been over a year. Would you add your vote so it gets slightly higher priority?

**Pull request closed without merging**
