### PR TITLE
Fix broken url in docs

### PR DESCRIPTION
**Pull request by saintmalik**
## Summary

Easy navigation and easy reading for others

### CODE REVIEW

**Review by ilmat192 — APPROVED** [review]

**Comment by ilmat192** [comment]
@saintmalik Thank you for the contribution! The change is ok but Kotlin 1.4.21 has been already released and there are no plans regarding new bugfix releases for 1.4.20. So could you please change the target branch to `master`?

**Comment by saintmalik** [comment]
Okay I will do that

**Comment by saintmalik** [comment]
> @saintmalik Thank you for the contribution! The change is ok but Kotlin 1.4.21 has been already released and there are no plans regarding new bugfix releases for 1.4.20. So could you please change the target branch of this PR to `master`?

After changing the target branch to master, alot of conflicts popped out, what should i do now?

**Comment by ilmat192** [comment]
Oh, I see. The easiest way to fix it is to create a new branch from the current `master` and cherry-pick your commit into it. Feel free to close this PR and create a new one for the new branch.

**Comment by saintmalik** [comment]
Thanks for the tip!, Will do that now

**Comment by saintmalik** [comment]
> Oh, I see. The easiest way to fix it is to create a new branch from the current `master` and cherry-pick your commit into it. Feel free to close this PR and create a new one for the new branch.

Here is the pull request #4643

**Pull request closed without merging**
