### PR TITLE
mingw_x86 target

### PR DESCRIPTION
**Pull request by msink**
toolchain: [msys2-mingw-w64-i686-gcc-7.3.0-clang-llvm-lld-6.0.1.zip](https://yadi.sk/d/krBzyqeAqr2x8g)

### CODE REVIEW

**Comment by olonho** [comment]
It will unlikely work out of the box, runtime is not ready for windows_x86 yet.

**Comment by msink** [comment]
There are many votes for it in #939, including mine :)
So at least - should arch be named `X86`?

**Comment by msink** [comment]
Great, it can succesfully create 32-bit .dll:
`kotlinc test.kt -target mingw_x86 -produce dynamic -o test`

And I really needed .dll, not .exe, so it already works for me.

**Comment by msink** [comment]
Just ont problem - had to restart `gradlew bundle` several times - it fails randomly, probably because of low memory. Restarting helps.

**Comment by olonho** [comment]
OK, we will try to get this merged eventually.

**Comment by sbogolepov** [comment]
Thank you, merged with #2656.

**Pull request closed without merging**
