### PR TITLE
Smarter process abandoned foreign references.

### PR DESCRIPTION
**Pull request by olonho**

### CODE REVIEW

**Comment by SvyatoslavScherbina** [comment]
This PR lacks relevant test.

**Comment by olonho** [comment]
Got ideas how to test it without interop?

**Comment by SvyatoslavScherbina** [comment]
> Got ideas how to test it without interop?

No, but isn't testing it with interop an option?

**Comment by olonho** [comment]
OK, will think of properly testing it somehow.

**Pull request merged**
