### PR TITLE
Update build logic

### PR DESCRIPTION
**Pull request by IgorGanapolsky**
Migrate to AndroidX libraries for android client.
Fix gradle.properties to build in XCode.
Remove deprecated `jcenter()` package dependency, as it is deprecated.

### CODE REVIEW

**Comment by SvyatoslavScherbina** [comment]
Thank you for your contribution!
As [stated in the readme](https://github.com/JetBrains/kotlin-native#kotlinnative), the development of the kotlin-native master branch was moved to https://github.com/JetBrains/kotlin (see [kotlin-native/](https://github.com/JetBrains/kotlin/tree/master/kotlin-native) subdirectory). Please move this PR to kotlin repo.

**Comment by IgorGanapolsky** [comment]
@SvyatoslavScherbina Unfortunately that Kotlin repo cannot be built.  
> Required environment variables are missing: JDK_9

**Comment by SvyatoslavScherbina** [comment]
It is not required to build Kotlin in order to build the sample: just remove this line: https://github.com/JetBrains/kotlin/blob/75d9cd3814c95dc64227ef6bbe2854e8bab754d3/kotlin-native/samples/calculator/gradle.properties#L15

**Comment by IgorGanapolsky** [comment]
Tried that.  Still expects **JDK_9**.  That README file states:
> Build environment requirements

**Comment by SvyatoslavScherbina** [comment]
> Tried that. Still expects **JDK_9**. That README file states:

I can't confirm this.

> That README file states:
> Build environment requirements

Do you refer to https://github.com/JetBrains/kotlin#build-environment-requirements? In this case, again, if you remove [that line](https://github.com/JetBrains/kotlin/blob/75d9cd3814c95dc64227ef6bbe2854e8bab754d3/kotlin-native/samples/calculator/gradle.properties#L15) from `gradle.properties`, you won't be required to build Kotlin itself.

Please try to remove the line and then build only the calculator sample.

**Pull request closed without merging**
