### PR TITLE
[typo] Fix NSNumber markdown table typo

### PR DESCRIPTION
**Pull request by masters3d**

### CODE REVIEW

**Comment by SvyatoslavScherbina** [comment]
This is not a typo. Kotlin primitives types are represented as `NSNumber` or primitive types in both Swift and Obj-C.

**Comment by masters3d** [comment]
The table doesn’t look formatted correctly.

**Comment by SvyatoslavScherbina** [comment]
Feel free to fix it if you think so.

**Comment by masters3d** [comment]
This is the fix. \ vs |

**Comment by SvyatoslavScherbina** [comment]
No it is not. See https://github.com/JetBrains/kotlin-native/pull/4372#issuecomment-701927178.
"Swift" column should contain **both** "Primitive type" and "NSNumber".

**Comment by masters3d** [comment]
it was confusing to me that objective column was empty. looks like primitive types are not supported in objc then.

**Pull request closed without merging**
