### PR TITLE
[debug] add test for pretty-printers

### PR DESCRIPTION
**Pull request by matklad**
This adds tests for our Python debugger pretty printers. 

Note that these test **will** fail with the current master branch, because https://github.com/JetBrains/kotlin-native/commit/bbeefb0b561fdb5afe260cd5429f7a1c1bea7753 has broken the pretty printers.

### CODE REVIEW

**Comment by matklad** [comment]
cc @vvlevchenko

**Comment by matklad** [comment]
Ok, should be good to go now, thanks @vvlevchenko !

**Comment by olonho** [comment]
@matklad please close the PR, if no longer relevant.

**Comment by matklad** [comment]
This PR should be merged because it contains both a fix by @vvlevchenko and a regression test.

**Pull request merged**
