### PR TITLE
 Disable incorrect optimization for varargs and list of string literals

### PR DESCRIPTION
**Pull request by SvyatoslavScherbina**

### CODE REVIEW

**Comment by benasher44** [comment]
Are there plans to re-enable this? I ended up offloading some calls to C functions with varargs into an inline C function in a .def file, which got me a pretty significant performance boost

**Comment by SvyatoslavScherbina** [comment]
@benasher44 this patch shouldn't affect performance of C calls, it is mostly related to pure Kotlin function calls.
Performance of calls to C variadic functions is likely to become significantly better in Kotlin 1.3.30.

**Comment by benasher44** [comment]
Ah awesome! Looking forward to that. Is that a PR that has landed already?

**Comment by SvyatoslavScherbina** [comment]
This one: #2528 (merged month ago).

**Comment by benasher44** [comment]
Thanks!

**Comment by benasher44** [comment]
Wow libffi is no longer needed??

**Comment by SvyatoslavScherbina** [comment]
Exactly!

**Comment by benasher44** [comment]
👏👏👏👏

**Pull request merged**
