### PR TITLE
zephyr: hello world

### PR DESCRIPTION
**Pull request by msink**

### CODE REVIEW

**Comment by msink** [comment]
[dependencies](https://yadi.sk/d/OzCkdTUf3QaDGP)

**Comment by msink** [comment]
[zephyr-host-tools-1-linux](https://yadi.sk/d/0YlJyS3_3SP9En) содержит только:
- cmake 3.8.2 - в большинстве линуксов 3.5,  а zephyr требует 5.8.1+
- mconf - чтобы работал `make menuconfig` 

Куда правильней все это положить?
Или вообще убрать, пусть юзер сам разбирается?

**Comment by msink** [comment]
I hope now it's ready for merge or review.

**Comment by msink** [comment]
Rebased.

**Comment by alexander-gorshenev** [comment]
@msink Mike, we, probably, going to accept these changes in separate portions. Restructuring your fix and the compiler as needed.

**Comment by jwoolston** [comment]
@alexander-gorshenev Would it be worthwhile to split out the changes @msink made for adding the QEMU emulator? If so I am happy to do it (I'm going to for my own needs anyway).

**Comment by msink** [comment]
If you care to cleanup and finalize this stuff - I will be glad, no objections from me.

**Comment by SvyatoslavScherbina** [comment]
Superseded by #2485.

**Pull request closed without merging**
