### PR TITLE
[kotlin compiler][update] 1.4.0-dev-4271

### PR DESCRIPTION
**Pull request by vvlevchenko**
* 9904304e071 - (tag: build-1.4.0-dev-4271) (CoroutineDebugger) StackFrameInterceptor service added to KotlinPositionManager, dependency cleanup (vor 23 Stunden) <Vladimir Ilmov>
* 0af61293d5d - (tag: build-1.4.0-dev-4269) Fix ExtensionTestUtil compilation for 191; CustomUsageSearcherTest compilation for 201 (vor 2 Tagen) <Vladimir Dolzhenko>
* 57fd449288a - (tag: build-1.4.0-dev-4260) Minor, add check of const field modifiers to codegen test (vor 3 Tagen) <Alexander Udalov>
* 1e3e791d432 - (tag: build-1.4.0-dev-4257) Fix compilation error in `MLCompletionForKotlin` bunch files (vor 3 Tagen) <Roman Golyshev>
* 9daed1f2c60 - (tag: build-1.4.0-dev-4256, tag: build-1.4.0-dev-4252) Revert "[FIR-TEST] Move FIR ide tests to separate module" (vor 3 Tagen) <Dmitriy Novozhilov>
* bdd88e16553 - (tag: build-1.4.0-dev-4249) JVM_IR: place suspend markers in faux lambdas around inline references (vor 3 Tagen) <pyos>
* f29e665dce9 - (tag: build-1.4.0-dev-4245) Add "ML completion for Kotlin" experimental feature checkbox (vor 3 Tagen) <Roman Golyshev>
* 4c6ea7c26a4 - (tag: build-1.4.0-dev-4241) KT-36808 Sink down member function `Flow.collect` in the completion (vor 3 Tagen) <Roman Golyshev>
* d27954a6d4c - (tag: build-1.4.0-dev-4237, tag: build-1.4.0-dev-4234) [IR] Use erased types in backing field initializer in case of generic delegated property (vor 3 Tagen) <Roman Artemev>
* 13a73b67de4 - [IR] Fix IrPropertyReference for delegated property (vor 3 Tagen) <Roman Artemev>
* 34c17e2bed0 - [KLIB] Add regression to about VarAsFun type parameter leak (vor 3 Tagen) <Roman Artemev>
* 8c1772d623d - [KLIB] Add regression test (vor 3 Tagen) <Roman Artemev>
* 09239743c1d - (tag: build-1.4.0-dev-4228) Fix compilation KotlinCopyPasteReferenceProcessor for 191, 192 (vor 3 Tagen) <Vladimir Dolzhenko>
* 123311007b8 - (tag: build-1.4.0-dev-4227) Fix compilation CustomUsageSearcherTest for 191, 201 (vor 3 Tagen) <Vladimir Dolzhenko>
* 31776d9a3bd - (tag: build-1.4.0-dev-4226) [CFA] Mark arguments of all annotation calls as `USED_AS_EXPRESSION` (vor 3 Tagen) <Dmitriy Novozhilov>
* b9ffed3f04a - (tag: build-1.4.0-dev-4225) Replace `ConfigurationFactory` with `SimpleConfigurationType` (vor 3 Tagen) <Dmitry Gridin>
* 43d6ddd4058 - (tag: build-1.4.0-dev-4220) Minor, fix typo in KotlinChunk.kt (vor 3 Tagen) <Alexander Udalov>
* 20c4a7b2443 - (tag: build-1.4.0-dev-4217) [FIR2IR] Introduce staged transformation (first step) (vor 3 Tagen) <Mikhail Glukhikh>
* a9f7ff254b8 - (tag: build-1.4.0-dev-4215) Add -Xno-optimized-callable-references to disable KT-27362 optimization (vor 3 Tagen) <Alexander Udalov>
* ae4629a5a60 - (tag: build-1.4.0-dev-4214) Fetch analysis results if it is available (vor 3 Tagen) <Vladimir Dolzhenko>
* 7cf8697e309 - (tag: build-1.4.0-dev-4209) [JS BEs] use star projection when type parameter used recursively (vor 3 Tagen) <Zalim Bashorov>
* 8c7562d338c - [CJS BE] don't crash when intersection types passed for a reified parameter (vor 3 Tagen) <Zalim Bashorov>
* 415893b8aab - [JS CLI] revert disabling NI by default (vor 4 Tagen) <Zalim Bashorov>
* 5188bc6584d - [JS FE] remove unused ReleaseCoroutinesDisabledLanguageVersionSettings (vor 4 Tagen) <Zalim Bashorov>
* 87242b419aa - (tag: build-1.4.0-dev-4207) Improvements in KotlinCopyPasteReferenceProcessor (vor 4 Tagen) <Vladimir Dolzhenko>
* b1c4b5f51ba - (tag: build-1.4.0-dev-4203) NI: Analyze lambdas which are return arguments of another lambda (vor 4 Tagen) <Victor Petukhov>
* 426738b7d49 - (tag: build-1.4.0-dev-4199) JVM_IR: Cache stubs in CollectionStubMethodLowering (vor 4 Tagen) <Georgy Bronnikov>
* 92268c8144d - JVM_IR: do not generate excessive stubs for immutable collections (vor 4 Tagen) <Georgy Bronnikov>
* 9955f342c0c - (tag: build-1.4.0-dev-4189) [FIR-TEST] Move FIR ide tests to separate module (vor 4 Tagen) <Dmitriy Novozhilov>
* b1fac4e7219 - (tag: build-1.4.0-dev-4186) Implement reduceIndexedOrNull and reduceRightIndexedOrNull #KT-36866 (vor 4 Tagen) <Abduqodiri Qurbonzoda>
* b60633d79a0 - Add associateWith to Array<T> #KT-30372 (vor 4 Tagen) <Abduqodiri Qurbonzoda>
* e632d589360 - (tag: build-1.4.0-dev-4185) Nullable Array.contentEquals/contentHashCode/contentToString #KT-34161 (vor 4 Tagen) <Abduqodiri Qurbonzoda>
* 179ec41a6b4 - (tag: build-1.4.0-dev-4183) [JS BEs] Generate tests for whole "codegen/boxInline" (vor 4 Tagen) <Zalim Bashorov>
* fe3a81ebc92 - [JS BEs] Minor: fix warnings in abstract classes for generated tests (vor 4 Tagen) <Zalim Bashorov>
* c664bfc62bb - (tag: build-1.4.0-dev-4179) Update property delegate test data (vor 4 Tagen) <Abduqodiri Qurbonzoda>
* 3762b5cba7c - (tag: build-1.4.0-dev-4170) Minor, remove extraneous field CodegenTestCase.coroutinesPackage (vor 4 Tagen) <Alexander Udalov>
* 244db9bcf9e - JVM IR: don't rename fake overrides for fields (vor 4 Tagen) <Alexander Udalov>
* 9ceca69154c - (tag: build-1.4.0-dev-4169) Do not stop searchTextOccurrences when isSearchForTextOccurrences is false (vor 4 Tagen) <kovalp>
* 6fd8ccc293e - (tag: build-1.4.0-dev-4166) [FIR2IR] Support (simple) conversion of captured types (vor 4 Tagen) <Mikhail Glukhikh>
* e919e7b79a8 - (tag: build-1.4.0-dev-4157) [Gradle][Native][Cache] Don't skip metadata-based interop libraries (vor 4 Tagen) <Sergey Bogolepov>
* c0b15b1768e - (tag: build-1.4.0-dev-4155) KT-37448 'this' in delegating constructor call may refer to outer object (vor 4 Tagen) <Dmitry Petrov>
* 2bd58727823 - (tag: build-1.4.0-dev-4152) 201: [Gradle, JS] Non jvm configurator from xml including (vor 4 Tagen) <Ilya Goncharov>
* dc2dd2e3e30 - [Gradle, JS] Remove idle test runner (vor 4 Tagen) <Ilya Goncharov>
* 8c8307d0d2e - 201: [Gradle, JS] Remove redundant non jvm configurator for 201 (vor 4 Tagen) <Ilya Goncharov>
* 857f3335bb6 - [Gradle, JS] TestFramework is public to detect it in debug extension (vor 4 Tagen) <Ilya Goncharov>
* 3728dd45ce8 - [Gradle, JS] Remove redundant hacks for debug (vor 4 Tagen) <Ilya Goncharov>
* 7efab887aa5 - (tag: build-1.4.0-dev-4151) JVM_IR: Do not generate accessor for private function (vor 4 Tagen) <Ilmir Usmanov>

### CODE REVIEW

**Comment by sbogolepov** [comment]
https://github.com/JetBrains/kotlin-native/commit/f7aedf9174882617defb412b6e598af47d16d9d0?

**Comment by vvlevchenko** [comment]
> [f7aedf9](https://github.com/JetBrains/kotlin-native/commit/f7aedf9174882617defb412b6e598af47d16d9d0)?

as mentioned in commit comment it's workaround for ambiguity of KLIB_INTERROP_IR_PROVIDER.

**Comment by PavelPunegov** [comment]
> > [f7aedf9](https://github.com/JetBrains/kotlin-native/commit/f7aedf9174882617defb412b6e598af47d16d9d0)?
> 
> as mentioned in commit comment it's workaround for ambiguity in resolving of KLIB_INTERROP_IR_PROVIDER.

Why not just remove the duplicated const?

**Comment by vvlevchenko** [comment]
> > > [f7aedf9](https://github.com/JetBrains/kotlin-native/commit/f7aedf9174882617defb412b6e598af47d16d9d0)?
> > 
> > 
> > as mentioned in commit comment it's workaround for ambiguity in resolving of KLIB_INTERROP_IR_PROVIDER.
> 
> Why not just remove the duplicated const?

Thanks Pavel? Haven't noticed this revision in the mirror branch.

**Pull request merged**
